# -*- coding: utf-8 -*-
"""
Regression tests: parsing saved Wikipedia tables must reproduce the verified data in data/.
Fixtures are generated by tests/make_fixtures.py.
"""

import json
import os

import pytest
from bs4 import BeautifulSoup

import master_scraper
from conftest import DATA_DIR, FIXTURES_DIR
from make_fixtures import FIXTURES

CATEGORIES = ['best-film', 'best-director', 'best-actor', 'best-actress']


def load_season(year):
    with open(os.path.join(DATA_DIR, f'data_{year - 1}_{year}.json'), encoding='utf-8') as f:
        return json.load(f)


def entries_for(entries, award):
    return {(e['name'], e.get('film', ''), e['awards'][award])
            for e in entries if award in e.get('awards', {})}


@pytest.mark.parametrize('award,year', FIXTURES)
def test_scrape_award_matches_verified_data(award, year, monkeypatch):
    path = os.path.join(FIXTURES_DIR, f'{award}_{year}.html')
    with open(path, encoding='utf-8') as f:
        html = f.read()
    monkeypatch.setattr(master_scraper, 'fetch_page', lambda url: BeautifulSoup(html, 'html.parser'))

    result = master_scraper.scrape_award(award, year)
    expected = load_season(year)

    for cat in CATEGORIES:
        assert entries_for(result.get(cat, []), award) == entries_for(expected[cat], award), cat
